// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbstKCDYgbF2do3g2RWeON1beqdCDx4dA',
    appId: '1:275145323529:web:47c0db9573d1aa926d74d8',
    messagingSenderId: '275145323529',
    projectId: 'emerald-tasks',
    authDomain: 'emerald-tasks.firebaseapp.com',
    storageBucket: 'emerald-tasks.firebasestorage.app',
    measurementId: 'G-N54JLWMV17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl5NzhNreeiQVbCAGrw87aEd_mFfWI5p0',
    appId: '1:275145323529:android:c7b432ee898fa0e46d74d8',
    messagingSenderId: '275145323529',
    projectId: 'emerald-tasks',
    storageBucket: 'emerald-tasks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLiYiz7jA0kiVxaUtNXS0f3fJFmKSZ-3o',
    appId: '1:275145323529:ios:f18a1330c709c5ad6d74d8',
    messagingSenderId: '275145323529',
    projectId: 'emerald-tasks',
    storageBucket: 'emerald-tasks.firebasestorage.app',
    iosClientId: '275145323529-8tt90uesrhu48eh65rnjt5s921ahfhan.apps.googleusercontent.com',
    iosBundleId: 'com.example.emeraldTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLiYiz7jA0kiVxaUtNXS0f3fJFmKSZ-3o',
    appId: '1:275145323529:ios:f18a1330c709c5ad6d74d8',
    messagingSenderId: '275145323529',
    projectId: 'emerald-tasks',
    storageBucket: 'emerald-tasks.firebasestorage.app',
    iosClientId: '275145323529-8tt90uesrhu48eh65rnjt5s921ahfhan.apps.googleusercontent.com',
    iosBundleId: 'com.example.emeraldTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbstKCDYgbF2do3g2RWeON1beqdCDx4dA',
    appId: '1:275145323529:web:0ac9ea94760d958f6d74d8',
    messagingSenderId: '275145323529',
    projectId: 'emerald-tasks',
    authDomain: 'emerald-tasks.firebaseapp.com',
    storageBucket: 'emerald-tasks.firebasestorage.app',
    measurementId: 'G-3LB6GNFHSH',
  );

}