// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMC3R6uF2jkfpgl9rK-BZvDHcf6V-3bQg',
    appId: '1:784560926437:web:c6eac8f396fa566bdc2e0c',
    messagingSenderId: '784560926437',
    projectId: 'emerald-ai-b49af',
    authDomain: 'emerald-ai-b49af.firebaseapp.com',
    storageBucket: 'emerald-ai-b49af.firebasestorage.app',
    measurementId: 'G-TR405TBE1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbx9wvwsL6M4x5c4SJJhyPfCUSoUzFYBw',
    appId: '1:784560926437:android:5a80eeee3ff09aafdc2e0c',
    messagingSenderId: '784560926437',
    projectId: 'emerald-ai-b49af',
    storageBucket: 'emerald-ai-b49af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Gmyr3938p36Fa9YGVFt5WGNLKaQ-VMg',
    appId: '1:784560926437:ios:e222ee8181f32c77dc2e0c',
    messagingSenderId: '784560926437',
    projectId: 'emerald-ai-b49af',
    storageBucket: 'emerald-ai-b49af.firebasestorage.app',
    iosClientId: '784560926437-mto7e659srqq22sceop5sq53cenknlso.apps.googleusercontent.com',
    iosBundleId: 'com.example.emeraldTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Gmyr3938p36Fa9YGVFt5WGNLKaQ-VMg',
    appId: '1:784560926437:ios:e222ee8181f32c77dc2e0c',
    messagingSenderId: '784560926437',
    projectId: 'emerald-ai-b49af',
    storageBucket: 'emerald-ai-b49af.firebasestorage.app',
    iosClientId: '784560926437-mto7e659srqq22sceop5sq53cenknlso.apps.googleusercontent.com',
    iosBundleId: 'com.example.emeraldTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMC3R6uF2jkfpgl9rK-BZvDHcf6V-3bQg',
    appId: '1:784560926437:web:d3ba1c8d264f023cdc2e0c',
    messagingSenderId: '784560926437',
    projectId: 'emerald-ai-b49af',
    authDomain: 'emerald-ai-b49af.firebaseapp.com',
    storageBucket: 'emerald-ai-b49af.firebasestorage.app',
    measurementId: 'G-WNMS90VB4Z',
  );

}